from .tag_controller import tag_bp
from .user_controller import user_bp
from .blog_controller import blog_bp
from .admin_controller import admin_bp
from .curso_controller import curso_bp
from .video_controller import video_bp
from .login_controller import login_bp
from .pregunta_controller import pregunta_bp
from .respuesta_controller import respuesta_bp
from .searchbar_controller import searchbar_bp