"""Check for model and database synchronization

Revision ID: 33db766ba35f
Revises: 4ea469d0d482
Create Date: 2024-09-21 13:21:59.092201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33db766ba35f'
down_revision = '4ea469d0d482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_respuesta', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_respuesta_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_pregunta', ['quiz_respuesta_pregunta_id'], ['quiz_pregunta_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_respuesta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_respuesta_ibfk_1', 'quiz_pregunta', ['quiz_respuesta_pregunta_id'], ['quiz_pregunta_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
