"""change blog datatype

Revision ID: 344d573b7ce6
Revises: 4914818856fb
Create Date: 2024-10-08 02:28:00.890551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '344d573b7ce6'
down_revision = '4914818856fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('blog_img',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('tag_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('tag_name', ['tag_name'], unique=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('blog_img',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
