"""Removed unique constraint from tag_name

Revision ID: 4914818856fb
Revises: c78346dfc359
Create Date: 2024-09-24 15:01:02.718980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4914818856fb'
down_revision = 'c78346dfc359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_respuesta', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_respuesta_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_pregunta', ['quiz_respuesta_pregunta_id'], ['quiz_pregunta_id'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('tag_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('tag_name', ['tag_name'], unique=True)

    with op.batch_alter_table('quiz_respuesta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_respuesta_ibfk_1', 'quiz_pregunta', ['quiz_respuesta_pregunta_id'], ['quiz_pregunta_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
