"""migration

Revision ID: 85ce452c297c
Revises: 
Create Date: 2024-09-20 14:51:34.620512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ce452c297c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_name', sa.String(length=125), nullable=False),
    sa.Column('admin_email', sa.String(length=125), nullable=False),
    sa.Column('admin_pwd', sa.String(length=225), nullable=False),
    sa.Column('admin_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('blog',
    sa.Column('blog_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blog_title', sa.String(length=255), nullable=False),
    sa.Column('blog_content', sa.Text(), nullable=False),
    sa.Column('blog_img', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('blog_id'),
    sa.UniqueConstraint('blog_id')
    )
    op.create_table('curso',
    sa.Column('curso_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curso_name', sa.String(length=255), nullable=False),
    sa.Column('curso_description', sa.Text(), nullable=False),
    sa.Column('curso_level', sa.String(length=80), nullable=False),
    sa.Column('curso_img', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('curso_id'),
    sa.UniqueConstraint('curso_id')
    )
    op.create_table('quiz_pregunta',
    sa.Column('quiz_pregunta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_pregunta_nivel', sa.String(length=255), nullable=False),
    sa.Column('quiz_pregunta_contenido', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('quiz_pregunta_id'),
    sa.UniqueConstraint('quiz_pregunta_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=125), nullable=False),
    sa.Column('user_email', sa.String(length=125), nullable=False),
    sa.Column('user_pwd', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('video',
    sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_title', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('video_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('video_id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('quiz_respuesta',
    sa.Column('quiz_respuesta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_respuesta_opcion', sa.String(length=80), nullable=False),
    sa.Column('quiz_respuesta_contenido', sa.Text(), nullable=False),
    sa.Column('quiz_respuesta_correcta', sa.Boolean(), nullable=False),
    sa.Column('quiz_respuesta_pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_respuesta_pregunta_id'], ['quiz_pregunta.quiz_pregunta_id'], ),
    sa.PrimaryKeyConstraint('quiz_respuesta_id'),
    sa.UniqueConstraint('quiz_respuesta_id')
    )
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('tag_curso_id', sa.Integer(), nullable=True),
    sa.Column('tag_quiz_pregunta_id', sa.Integer(), nullable=True),
    sa.Column('tag_blog_id', sa.Integer(), nullable=True),
    sa.Column('tag_video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_blog_id'], ['blog.blog_id'], ),
    sa.ForeignKeyConstraint(['tag_curso_id'], ['curso.curso_id'], ),
    sa.ForeignKeyConstraint(['tag_quiz_pregunta_id'], ['quiz_pregunta.quiz_pregunta_id'], ),
    sa.ForeignKeyConstraint(['tag_video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('quiz_respuesta')
    op.drop_table('video')
    op.drop_table('user')
    op.drop_table('quiz_pregunta')
    op.drop_table('curso')
    op.drop_table('blog')
    op.drop_table('admin')
    # ### end Alembic commands ###
